export const strings = {
  solanaBenchmark: {
    start: 'Start benchmark',
    resume: 'Resume benchmark',
    running: 'Running benchmark',
    requests: 'RPC requests sent',
    saved: 'Results and progress saved locally. Refreshing this page is safe.',
    comparisonNote:
      'Price differences compare USDC quotes only. SOL quotes need a separate USD conversion.',
    error: 'Benchmark error',
    errors: 'Errors saved',
    payloads: 'Solana RPC payloads',
    failures: 'Unavailable trades by reason',
    eyebrow: 'EXPERIMENTAL · RESEARCH ONLY',
    title: 'Solana delayed-price benchmark',
    subtitle: 'Compare a Solana RPC price provider with saved Dune delayed-copy matches.',
    refresh: 'Refresh benchmark',
    loading: 'Reading benchmark report…',
    unavailable:
      'No benchmark report is available yet. Run the prototype benchmark to populate this view.',
    provider: 'Provider',
    publicMainnet: 'Helius RPC (API key required)',
    history: 'History preflight',
    pass: 'PASS',
    fail: 'FAIL',
    notRun: 'NOT RUN',
    benchmark: 'Benchmark parity',
    legsTested: 'Legs tested',
    solanaFound: 'Solana found',
    duneFound: 'Dune found',
    bothFound: 'Both found',
    sameSignature: 'Same signature',
    medianDifference: 'Median price difference',
    p95Difference: 'P95 price difference',
    generatedAt: 'Generated',
    notAvailable: '—',
  },
  liveEvaluation: {
    title: 'Live Evaluation',
    subtitle: 'Current wallet view with historical winner proof',
    disclaimer: 'Uses saved GMGN context and persisted Dune evidence · never fetches Dune',
    addressLabel: 'Wallet address',
    addressPlaceholder: 'Solana wallet address',
    evaluateButton: 'Evaluate',
    evaluatingButton: 'Evaluating…',
    fetchingNotice: 'Reading saved GMGN and delayed-copy evidence…',
    verdictLabels: {
      pass: 'Pass',
      reject: 'Reject',
      insufficient_evidence: 'Insufficient Evidence',
    },
    confidenceLabel: 'Confidence',
    evidenceLevelLabel: 'Evidence level',
    profileStatusLabel: 'Pattern Discovery profile',
    profileStatus: {
      loaded: 'Loaded (current)',
      stale: 'Loaded (stale — evidence has changed since this profile was computed)',
      unavailable: 'Unavailable',
    },
    componentScoreLabels: {
      historicalProfitability: 'Historical profitability',
      consistency: 'Consistency',
      robustness: 'Robustness',
      copyability: 'Copyability',
    },
    componentScoreDescriptions: {
      historicalProfitability:
        'GMGN-realized median return — not Decision Lab’s Dune-simulated Edge.',
      consistency: 'Share of saved weekly/monthly periods with a positive median return.',
      robustness: 'Performance after removing the single best token.',
      copyability:
        'Holding-time proxy, reduced by promoted hyperactivity/fast-trading penalties. No Dune coverage term.',
    },
    overallScoreLabel: 'Estimated overall score',
    weightingUnavailable: 'No validated weighting exists — an overall score is not produced.',
    positiveReasonsTitle: 'Main positive reasons',
    riskReasonsTitle: 'Main risk/rejection reasons',
    noReasons: 'None.',
    gmgnStatsTitle: '30-day GMGN reference stats',
    rulesAppliedTitle: 'Pattern Discovery rules that affected the result',
    rulesUnavailableTitle: 'Promoted rules not applied',
    rulesUnavailableReasons: {
      'no-gmgn-mapping': 'No standing-wallet equivalent',
      'condition-shape-not-modeled': 'Condition shape not modeled',
      'insufficient-wallet-data': 'Insufficient wallet data',
    },
    noRulesApplied: 'No promoted rule affected this result.',
    noRulesUnavailable: 'None.',
    historyTitle: 'Evaluation history',
    historyCaption:
      'Each evaluation is compared with the immediately older evaluation for this wallet. Higher score is better.',
    historyEmpty: 'No prior evaluation history is available yet.',
    historyFirst: 'First evaluation',
    historySourceLive: 'Live Evaluation',
    historySourceDecisionLab: 'Decision Lab',
    emptyState: 'Enter a wallet address and click Evaluate.',
  },
  decisionLab: {
    copyingRisk: 'Copying risk',
    copyingRiskUnknown: 'Not enough data',
    copyingRiskLow: 'Looks copyable',
    copyingRiskWatch: 'Watch small trades',
    copyingRiskHigh: 'Copying risk',
    copyingRiskTitle: 'Whether trade size appears to threaten successful copying',
    bandDetails: 'Technical size-band evidence',
    scoreUnavailable: {
      missing: 'No simulation',
      partial: 'Partial evidence',
      insufficient: 'Insufficient evidence',
      complete: 'Gate failed',
    },
    analyticalSummary: 'Exploratory context only — these scores do not decide Winner Policy.',
    winnerPolicyIntro: 'Winner requires all four gates:',
    winnerPolicyGates: [
      '20+ completed copied-buy outcomes',
      '$100 portfolio ends above $100',
      'Dune evidence is actionable',
      'Profit survives without sub-60s trades',
    ],
    winnerPolicyScoreSummary:
      'Score: 70 delayed-copy points + 30 GMGN risk deductions. Holdouts are context only; GMGN can only lower the score.',
    winnerPolicyDetailHardGates: 'Hard gates',
    scoringTitle: 'How scoring works',
    scoringRule:
      'Each group receives a score from 0 to 100. The overall score is their weighted average; it is a comparison score, not a guaranteed profit forecast.',
    candidateGatesLabel: 'Final-candidate gates:',
    componentDescriptions: {
      edge: 'typical delayed-copy return',
      consistency: 'repeatability across saved periods',
      robustness: 'performance after removing the best token',
      copyability: 'holding time and validated trading penalties',
    },
    candidateGates:
      '20+ completed copied-buy outcomes, a canonical $100 portfolio ending above $100, and actionable Dune evidence.',
    missingEvidence:
      'Missing evidence stays unavailable—not zero—and prevents a raw overall score until all four components can be calculated.',
    weightsTitle: 'Weights currently in use',
    tableLegend: 'Scores run from 0 to 100; higher is better.',
    winnersOnly: 'Winners only',
    walletFilterPlaceholder: 'Filter wallet or name',
    exportSelectedWithDetails: 'Export selected with details',
    exportSelectedWinnersData: 'Export selected winners',
    scenarioReplay: {
      startingBankroll: 'Starting bankroll ($)',
      copyAmount: 'Copy amount per buy ($)',
      noDune: 'Replays stored delayed-copy prices. Changing values makes no Dune request.',
    },
    minimumCapital: {
      eyebrow: 'CAPITAL PLANNING · LOCAL ONLY',
      title: 'Minimum capital',
      description: 'Find the smallest practical bankroll for selected Winner wallets.',
      calculate: 'Calculate Minimum Capital for Selected',
      selected: (count: number) => `${count} selected`,
      chooseWinnerHint: 'Select Winner rows to calculate.',
      calculating: (done: number, total: number) => `Calculating ${done} / ${total} wallets…`,
      cached: 'Cached',
      needsCalculation: 'Needs calculation',
      outdated: 'Outdated',
      resultsTitle: 'Minimum capital results',
      close: 'Close',
      viewResults: 'View results',
      exportResults: 'Export results',
      resultsCopied: 'Results copied',
      copyResultsFailed: 'Clipboard unavailable.',
      calculated: 'Calculated',
      status: 'Status',
      wallet: 'Wallet',
      recommendedCapital: 'Recommended capital',
      copyAmount: 'Copy amount',
      copied: 'Copied',
      skipped: 'Skipped',
      deployed: 'Capital deployed',
      netPnl: 'Net P&L',
      cashSkips: 'Cash skips',
      fees: 'Fees',
      ending: 'Ending',
      return: 'Return',
      technicalMinimum: 'Technical minimum',
      maxOpenCapital: 'Max open capital',
      noConfigurations: 'No tested configurations were returned.',
      capital: 'Capital',
      buyAmount: 'Buy amount',
      detailsTitle: (wallet: string) => `Minimum Capital — ${wallet}`,
      testedConfigurations: 'Tested configurations',
      noResults: 'No minimum-capital results yet.',
      requestFailed: 'Minimum-capital calculation failed.',
    },
    generatedAt: (date: string) => `Report generated ${date}.`,
  },
  common: {
    signalTypeLabels: {
      '1': 'General price spike',
      '2': 'Dex ad placement',
      '3': 'Dex social-link update',
      '4': 'Dex trending bar',
      '5': 'Dex Boost',
      '6': 'Price up',
      '7': 'Price ATH',
      '8': 'Market-cap key level',
      '9': 'Live stream',
      '10': 'Bundler sell',
      '11': 'Community takeover',
      '12': 'Smart-money buy',
      '13': 'Platform call',
      '14': 'Large-amount buy',
      '15': 'Multiple buys',
      '16': 'Multiple large buys',
      '17': 'Bags Claim',
      '18': 'Pump Claim',
      '19': 'Platform call V2',
      '20': 'KOL buy',
      '21': 'Banker Claim',
    } as Record<string, string>,
    signalTypeDescriptions: {
      '1': 'Rapid K-line price movement. This records what happened, not a buy recommendation.',
      '2': 'DEX ad placement or paid visibility event. It is promotion, not proof of demand.',
      '3': 'DEX social-link metadata was updated. No trading direction is implied.',
      '4': 'Token appeared in a DEX trending bar or ranking surface.',
      '5': 'DEX Boost or boosted visibility event. The exact payment/threshold rule is not published here.',
      '6': 'Price-up threshold trigger. It confirms upward movement at the trigger time, not future performance.',
      '7': 'Token reached an all-time-high price trigger at the observed time.',
      '8': 'A recognized market-cap key level was crossed; the exact threshold is not published in the CLI docs.',
      '9': 'Live-stream or live-community event associated with the token.',
      '10': 'Sell activity attributed to bundler-linked wallets; it does not mean every holder is selling.',
      '11': 'Community takeover (CTO) event, indicating a project/community ownership change.',
      '12': 'Buy attributed by GMGN to a smart-money wallet classification. The wallet scoring rule is not published.',
      '13': 'GMGN platform call or promotion event; the exact trigger rule is not published.',
      '14': 'Buy classified as large amount. The amount threshold is not published in the CLI docs.',
      '15': 'Several buy events grouped into one signal. The exact count and time window are not published.',
      '16': 'Several large buys grouped into one signal. Count, amount, and time-window thresholds are not published.',
      '17': 'Bags Claim platform event.',
      '18': 'Pump Claim platform event.',
      '19': 'Platform call V2 event; the public docs do not specify how it differs from type 13.',
      '20': 'Buy attributed by GMGN to a KOL-labelled wallet. The KOL list and threshold are not published.',
      '21': 'Banker Claim platform event.',
    } as Record<string, string>,
    unmappedSignalType: 'Unmapped GMGN type',
    unknownSignalType: 'unknown signal type',
    patternFeatureLabels: {
      prior_wallet_trade_count: 'Previous wallet trades',
      prior_token_trade_count: 'Previous trades for this token',
      prior_wallet_buy_volume_usd: 'Previous wallet buy volume',
    } as Record<string, string>,
    unknownPatternFeature: 'Unknown feature',
    noSimpleRuleReported: 'No simple rule was reported.',
    correlationLowerOutcomes: 'Higher values → lower outcomes',
    correlationHigherOutcomes: 'Higher values → higher outcomes',
    hiddenLossLabels: {
      high: 'Hides real losses',
      moderate: 'Hides some losses',
      negligible: 'Safe to trust',
      unknown: 'Cannot tell',
    },
    freshnessNever: 'never',
    freshnessUnknown: 'unknown',
    freshnessMinutesAgo: (minutes: number) => `${minutes}m ago`,
    freshnessDaysAgo: (days: number) => `${days}d ago`,
    fetchTimeToday: 'Today',
    fetchTimeYesterday: 'Yesterday',
    fetchTimeDaysAgo: (days: number) => `${days} days ago`,
    emptyServerResponse: 'The server returned an empty or invalid response.',
    noResponseBodyStored: 'No response body stored yet.',
    startingBalance: 'Starting balance',
    duneCoverageNotMeasured: (period: string) =>
      `Dune ${period} coverage has not been measured yet.`,
    duneCoverageLabel: (period: string, matched: string, eligible: string, percent: string) =>
      `Dune ${period}: ${matched} of ${eligible} locally eligible round trips have usable prices (${percent}). GMGN's activity count includes events, so it is not the denominator.`,
    copyTradeEstimateConfidence: {
      seeded: 'a seeded guess — no completed fetch yet',
      low: 'a rough guess — only 1-2 completed fetches so far',
      medium: 'a reasonable guess — a handful of completed fetches so far',
      high: 'based on several completed fetches',
    },
    formatRule: {
      min_trades: 'not enough trades',
      min_days: 'not enough history',
      positive_median: 'median return is not positive',
      risk_flag: 'risk flag present',
    } as Record<string, string>,
    copyTradeVerdictLabel: {
      screen_pass: 'Screen pass',
      no: 'Screen fail',
      thin: 'Thin data',
      flagged: 'Flagged',
      descriptive_only: 'Descriptive only — not comparable',
    },
    eliminationReasons: {
      stronglyNegative30dPnl: 'Strongly negative 30d P&L',
      negativeDelayedCopyResult: 'Negative delayed-copy result',
      holdTimeShorterThanCopyDelay: 'Hold time shorter than copy delay',
    },
    subgroupPropertyLabels: {
      launchPlatform: 'Launch platform',
      tokenAge: 'Token age at signal',
      combined: 'All combined',
    },
    subgroupPropertyDescriptions: {
      launchPlatform: 'launch platform',
      tokenAge: 'token age',
      combined: 'launch platform × token age',
    },
    copyAddressLabel: (label: string) => `Copy ${label}`,
    walletAddressLabel: 'wallet address',
    walletIconAlt: (name: string) => `${name} icon`,
    saveRowAsJson: 'Save this row as JSON',
    infoTipDefaultLabel: 'More information',
    capitalPathUnavailable: 'No complete multi-day capital path is available for this trader',
    capitalPathNoData: 'No path',
    capitalPathResetZoom: 'Reset 100%',
    capitalPathTooltip: (fromDay: string, toDay: string, finalUsd: string) =>
      `$100 path: ${fromDay} → ${toDay}; final ${finalUsd}`,
    capitalPathAriaLabel: (finalUsd: string) => `$100 path ending at ${finalUsd}`,
    capitalPathPortfolioPoint: 'Portfolio point',
    duneQueried: (targets: number, batches: number, exhausted: boolean) =>
      `Queried Dune for ${targets} entry/exit price${targets === 1 ? '' : 's'} across ${batches} batch${batches === 1 ? '' : 'es'}.${exhausted ? ' More remain — run again to continue.' : ''}`,
    duneAllAlreadyQueried:
      'Every eligible trade for the current top traders has already been queried.',
  },
  imports: {
    duneCohortEyebrow: '01 · DUNE COHORT',
    duneCohortTitle: 'Import historical tokens',
    duneCohortTag: 'CSV / JSON',
    duneCohortIntro:
      'Choose an export from your computer. Duplicate files and token addresses are safely skipped; malformed rows remain in the audit log.',
    savingFile: (fileName: string) => `Saving ${fileName}…`,
    tokensStoredInSqlite: (count: string, plural: string) =>
      `${count} token${plural} stored in SQLite`,
    lastImportSummary: (
      fileName: string,
      imported: number,
      skipped: number,
      errors: number,
      archiveStatus: string,
      at: string,
    ) =>
      `Last import "${fileName}": +${imported} imported · ${skipped} skipped · ${errors} errors · ${archiveStatus} · ${at}`,
    duplicateFileAlreadyArchived: 'duplicate file, already archived',
    archivedToZip: 'archived to ZIP',
    archivePending: 'archive pending',
    persistsAcrossRefreshes:
      'Persists in SQLite across refreshes and restarts — import each export only once.',
    prescreenAuditLine: (selected: number, total: number, percent: string) =>
      `Current GMGN pre-screen: ${selected} of ${total} signal rows selected for the next Dune pass (${percent}). This cohort import changes the reference data only; it does not send a Dune request.`,
    chooseDuneExport: 'Choose a Dune export',
    nothingLeavesThisMachine: 'Nothing leaves this machine',
    manualOverrideEyebrow: 'MANUAL OVERRIDE',
    manualOverrideTitle: 'Paste a raw observation',
    manualOverrideTag: 'JSON',
    manualOverrideIntro:
      'Optional: paste one captured event by hand instead of using automated capture below. The normalized fields are only a convenience; the complete payload is always retained.',
    saveGmgnObservation: 'Save GMGN observation',
    targetedEnrichmentEyebrow: 'TARGETED ENRICHMENT',
    targetedEnrichmentTitle: 'Look up GMGN tokens in Dune',
    targetedEnrichmentTag: 'CSV / JSON',
    targetedEnrichmentIntro:
      "Most GMGN signals land on tokens the Dune cohort export never covered. Export the addresses GMGN has actually observed, look them up in Dune yourself, then upload the result here — it's stored separately from the original cohort and never overwrites an address already on file.",
    exporting: 'Exporting…',
    exportAddresses: 'Export addresses (.txt)',
    generating: 'Generating…',
    generateDuneQueryButton: 'Generate Dune query',
    copyQuery: 'Copy query',
    importingEnrichment: 'Importing enrichment…',
    lastEnrichment: (fileName: string) => `Last enrichment: ${fileName}`,
    noEnrichmentThisSession: 'No enrichment imported this session',
    enrichmentSummary: (imported: number, skipped: number, errors: number, at: string) =>
      `+${imported} imported · ${skipped} already on file · ${errors} errors · ${at}`,
    sameAuditTrail:
      'Same audit trail and archive as a cohort import, tagged dune-targeted-enrichment.',
    targetedLookupNote:
      'This targeted lookup enriches stored cohort metadata only; it does not automatically capture outcomes. Use Dune Capture to send the pre-screened queue.',
    chooseDuneLookupResult: 'Choose a Dune lookup result',
    gmgnBrowserCaptureEyebrow: 'GMGN BROWSER CAPTURE',
    gmgnBrowserCaptureTitle: 'Import website signal evidence',
    gmgnBrowserCaptureTag: 'JSON EXPORT',
    importingBrowserCapture: 'Importing browser capture…',
    lastUpload: (fileName: string) => `Last upload: ${fileName}`,
    noBrowserCaptureThisSession: 'No browser capture imported this session',
    rawJsonAvailable: 'The raw JSON remains available for later audit and replay.',
    duplicateFileImportedBefore:
      'This exact file was already imported before — nothing new was added and nothing was re-fetched. Safe to re-upload an old export by mistake.',
    newSignalsAdded: 'new signals added',
    alreadyCapturedSkipped: 'already captured — skipped',
    issueRows: 'issue rows',
    otherCapturesArchived: (count: number, windows: number, at: string) =>
      `${count} other endpoint capture(s) archived (not parsed) · ${windows} coverage window(s) · ZIP archived · ${at}`,
    rawEndpointsThisUpload: (
      radar: number,
      walletRank: number,
      smartMoney: number,
      twitter: number,
    ) =>
      `Raw endpoints this upload: ${radar} radar · ${walletRank} wallet-rank · ${smartMoney} smart-money · ${twitter} twitter`,
    issueDetails: (detail: string) => `Issue details: ${detail}`,
    prescreenAfterImport: (
      selected: number,
      selectedPercent: string,
      deferred: number,
      deferredPercent: string,
      tooFresh: number,
      tooFreshPercent: string,
      tooFreshHours: number,
      invalid: number,
      invalidPercent: string,
      alreadyMeasured: number,
      alreadyMeasuredPercent: string,
      maxSignalIds: number,
    ) =>
      `Pre-screen after import: ${selected} selected (${selectedPercent}) for Dune · ${deferred} deferred (${deferredPercent}) · ${tooFresh} waiting for the ${tooFreshHours}h buffer (${tooFreshPercent}) · ${invalid} invalid (${invalidPercent}) · ${alreadyMeasured} already measured (${alreadyMeasuredPercent}). Deferred repeats are later token/type observations; deferred budget rows are valid but outside the current ${maxSignalIds}-signal pass budget.`,
    chooseBrowserCaptureExports: 'Choose browser capture exports',
    selectOneOrMoreJson:
      'Select one or more JSON files; each is processed and archived separately.',
    savingToSqlite: (fileName: string) => `Saving ${fileName} to SQLite and creating an archive…`,
    imported: (imported: number, skipped: number, errors: number, archive: string) =>
      `Imported ${imported}; skipped ${skipped}; errors ${errors}. Archive: ${archive}`,
    alreadyArchived: 'already archived',
    noMissingAddressesToExport:
      'No GMGN-observed token addresses are missing from the cohort right now — nothing to export.',
    exportedAddresses: (exported: number, total: number, matched: number) =>
      `Exported ${exported} address(es) not yet in the Dune cohort (of ${total} GMGN-observed addresses total, ${matched} already matched). Look these up in Dune, then upload the result below.`,
    noMissingAddressesToQuery:
      'No GMGN-observed token addresses are missing from the cohort right now — nothing to query.',
    generatedDuneQuery: (count: number) =>
      `Generated a Dune query for ${count} address(es). Copy it below, run it in Dune, then upload the result.`,
    duneQueryCopied: 'Dune query copied to clipboard.',
    couldNotCopyQuery:
      'Could not copy automatically — select the query text below and copy it manually.',
    savingEnrichment: (fileName: string) => `Saving ${fileName} as targeted Dune enrichment…`,
    enrichmentImported: (imported: number, skipped: number, errors: number) =>
      `Enrichment imported ${imported}; skipped ${skipped}; errors ${errors}. Addresses already in the cohort were left untouched.`,
    gmgnObservationSaved: (id: number) => `GMGN observation #${id} saved. Raw payload preserved.`,
  },
  capture: {
    uploadExportIntro:
      'Upload an export produced by the authorized GMGN browser capture extension. Events are tagged',
    uploadExportIntroSuffix:
      ', stored through the same append-only signal path, and the complete upload is archived with a manifest. This does not scrape or infer anything.',
    prescreenAfterImportLabel: 'Pre-screen after import:',
    rawEndpointCollapsibleSummary:
      'Raw endpoint captures (radar / wallet rank / smart money / Twitter)',
    rawEndpointIntro:
      "Exploratory raw data captured alongside signals — GMGN's own trending-token radar, its public wallet leaderboard, per-wallet smart-money stats, and KOL/Twitter activity. Purely descriptive: nothing here is scored, ranked, or linked to captured signals.",
    importingBrowserResponse: (fileName: string) =>
      `Importing ${fileName} and preserving the raw browser response…`,
    browserCaptureAlreadyImported: 'Browser capture already imported',
    browserCaptureImported: 'Browser capture imported',
    browserCaptureResult: (label: string, imported: number, skipped: number, errors: number) =>
      `${label}: +${imported} signals · ${skipped} repeats · ${errors} issues. Raw upload archived.`,
    importingMultipleCaptures: (count: number) =>
      `Importing ${count} browser captures one by one; each raw upload will be archived separately.`,
    finishedImportingCaptures: (count: number) =>
      `Finished importing ${count} browser capture files. Each file was processed and archived independently.`,
  },
  analysis: {
    eyebrow: 'DESCRIPTIVE ANALYSIS',
    title: 'Captured-signal snapshot',
    tag: 'NO SCORING',
    intro:
      'This summarizes what is currently in the database. It describes the snapshot only; it does not decide whether any signal is good or bad.',
    signalsCaptured: 'signals captured',
    uniqueTokens: (count: number) => `${count} unique tokens`,
    signalsMatchedToDune: 'signals matched to Dune',
    unmatched: (count: number) => `${count} unmatched`,
    medianSignalMarketCap: 'median signal market cap',
    recordsWithMarketCap: (count: number) => `${count} records with market cap`,
    tokensWithMultipleSignals: 'tokens with multiple signals',
    maxPerToken: (count: number) => `max ${count} per token`,
    signalTypesHeading: 'Signal types',
    typeLabel: (type: string) => `Type ${type}`,
    sourcesHeading: 'Sources',
    timingHeading: 'Timing',
    observedRange: (from: string, to: string) => `Observed: ${from} → ${to}`,
    capturedRange: (from: string, to: string) => `Captured: ${from} → ${to}`,
    interpretationLimits: 'Interpretation limits:',
  },
  scoring: {
    eyebrow: 'EXPLORATORY SCORING',
    title: 'Signal data-readiness score',
    tag: 'PROVISIONAL',
    intro:
      'This is the first transparent scoring experiment. It scores how much supporting data we have for each signal—not whether the signal made money.',
    averageReadiness: 'average readiness',
    signalsScored: (count: number) => `${count} signals scored`,
    fullyDocumented: 'fully documented',
    allChecksPassed: 'all eight checks passed',
    pointsLegend:
      'Points: Dune match (2) · first-trade time · DEX · transaction · signal time · time order · market cap',
    columnSignal: 'Signal',
    columnType: 'Type',
    columnScore: 'Score',
    columnDune: 'Dune',
    columnEvidence: 'Evidence',
    missingAddress: 'missing address',
    matched: 'Matched',
    unmatched: 'Unmatched',
    tradeTime: 'trade time',
    dex: 'DEX',
    tx: 'tx',
    timeOrder: 'time order',
    marketCap: 'market cap',
    noSupportingFields: 'No supporting fields',
    important: 'Important:',
  },
  patterns: {
    snapshotSaved: 'Pattern snapshot saved.',
    eyebrow: 'SIGNAL PATTERN BREAKDOWN',
    title: 'Which signal types moved after the signal?',
    tag: 'DESCRIPTIVE',
    defaultDisclaimer:
      'Descriptive research only. This does not prove any signal type is profitable or predictive going forward.',
    statusLabel: 'Patterns status:',
    statusDetail: (computedAt: string, latestDuneRun: string) =>
      `computed ${computedAt} · latest Dune run ${latestDuneRun} · this report issues no new Dune request.`,
    upToDate: 'UP TO DATE',
    refreshNeeded: 'REFRESH NEEDED',
    coverageGate: (coveragePct: number, captureDates: number, analysisUnit: string) =>
      `V3 coverage gate: ${coveragePct}% fresh coverage across ${captureDates} fresh capture dates; analysis unit is ${analysisUnit}. Trade-age cutoffs are enforced before a comparison can count as fresh.`,
    rankedByMedianNote:
      'Ranked by median, not average — one outlier trade can swing an average heavily without reflecting a typical outcome.',
    viewingSnapshot: (id: number, time: string) => `Viewing saved snapshot #${id} from ${time}.`,
    backToLiveReport: 'Back to live report',
    noMeasuredOutcomesYet: 'No measured outcomes yet — measure some signals above first.',
    showingBestHorizon: 'Showing best reliable horizon:',
    highestMedianAmongTypes: 'highest median among signal types that pass every reliability gate',
    saving: 'Saving…',
    saveSnapshot: 'Save snapshot',
    signalsWithGenuineOutcome: 'signals with a genuine outcome',
    freshOfTotal: (fresh: number, total: number) =>
      `${fresh} of ${total} — the rest are missing or stale`,
    upOverallAt: (horizon: string) => `up overall at ${horizon}`,
    acrossAllTypesCombined: 'across all signal types combined',
    overallMedianReturn: 'overall median return',
    typicalOutcomeNote: 'the honest "typical outcome" number, not the average',
    showRowsWithInsufficientData: 'Show rows with insufficient data',
    hiddenByDefault: (count: number) => `${count} hidden by default`,
    columnSignalType: 'Signal type',
    columnBestHorizon: 'best horizon',
    columnN: 'n',
    columnFresh: 'fresh',
    columnTokens: 'tokens',
    columnMissing: 'missing',
    columnUpPercent: 'up %',
    columnMedian: 'median',
    columnP25Downside: 'p25 downside',
    columnWorst: 'worst',
    columnAverage: 'average',
    columnVerdict: 'verdict',
    overallRowLabel: 'Overall',
    columnWithData: 'with data',
    staleColumnTitle: 'No new trade before this checkpoint — excluded from up %/avg/median',
    columnStale: 'stale',
    tokensColumnTitle:
      'Distinct tokens behind the fresh comparisons — a lower number than n/fresh means the same token repeated',
    columnAvgReturn: 'avg return',
    columnMedianReturn: 'median return',
    repeatedTokensTitle:
      'Some tokens repeated this signal type more than once — these comparisons are not fully independent.',
    smallSampleTitle: (minReliableSample: number) =>
      `Fewer than ${minReliableSample} genuine (non-stale) comparisons — too small to trust as a pattern.`,
    smallSample: 'small sample',
    computedFromRuns: (computedAt: string, runCount: number, plural: string) =>
      `Computed ${computedAt} from ${runCount} archived Dune run${plural} already stored locally — no new Dune query is issued to build this report.`,
    savedSnapshots: (count: number) => `Saved snapshots (${count})`,
    snapshotSourceRuns: (id: number, time: string, count: number, plural: string) =>
      `#${id} · ${time} · ${count} source run${plural}`,
    view: 'View',
    subgroupBreakdownSummary: 'Subgroup breakdown: signal type × property (exploratory)',
    subgroupDefaultDisclaimer:
      'Descriptive research only. This does not prove any signal type + property combination is profitable or predictive going forward.',
    subgroupExplanation:
      "Limited to properties fixed at signal time (launch platform, token age) — fast-moving fields like live liquidity or volume are query-time snapshots, not verified trigger-time facts, so they're deliberately excluded from this breakdown for now. No statistical correction is applied for testing multiple cells at once — the cell count below is shown so a good-looking cell can be weighed against how many were tested. This view picks its own best horizon independently of the main table above — a standout combination can peak at a different horizon than the aggregate picture.",
    computing: 'Computing…',
    autoSelected: 'Auto-selected:',
    autoSelectedDetail: (
      horizon: string,
      cellCount: number,
      cellPlural: string,
      propertyDescription: string,
      excluded: number,
      excludedPlural: string,
    ) =>
      `(best reliable cell for this breakdown) · ${cellCount} cell${cellPlural} tested (signal type × ${propertyDescription}) · ${excluded} signal${excludedPlural} excluded (property not extractable, not guessed).`,
    cellColumnHeader: (propertyDescription: string) => `Cell (type × ${propertyDescription})`,
    noSubgroupHorizon:
      'No subgroup horizon currently passes all reliability gates (fresh sample, coverage, distinct tokens, and capture-date spread). The data remains stored for review.',
    measuredResults: (count: number) => `Measured results (${count})`,
    rowsPerPage: 'Rows per page',
    all: 'All',
    previous: 'Previous',
    pageOf: (page: number, total: number) => `Page ${page} of ${total}`,
    next: 'Next',
    clickToSort: 'Click to sort',
    noReliableComparisons: (horizon: string) =>
      `At ${horizon}, no signal type yet has enough genuine (non-stale) comparisons to call a pattern either way.`,
    noPositiveStandout: (horizon: string) =>
      `At ${horizon}, every signal type with enough data has a negative or flat median return — none stands out as positive.`,
    positiveTypesSummary: (
      horizon: string,
      positiveTypes: string,
      positiveIsSingle: boolean,
      negativeCount: number,
    ) =>
      `At ${horizon}: ${positiveTypes} ${positiveIsSingle ? 'is the only type' : 'are the only types'} with a positive median return; ${negativeCount} other type${negativeCount === 1 ? '' : 's'} with enough data ${negativeCount === 1 ? 'is' : 'are'} net-negative.`,
  },
  duneCapture: {
    activityRunningBatches: 'Dune measurement batches are running',
    activityCheckingRuns: 'Checking Dune runs for completion',
    activityRefreshingPlan: 'Refreshing the Dune measurement plan',
    activityLoadingEvidence: 'Loading saved Dune evidence',
    activityIdle: 'Dune Capture is idle',
    eyebrow: 'DUNE SIGNAL OUTCOME TIMELINE',
    title: 'Measure captured GMGN signals',
    tag: 'DUNE PRICE HISTORY',
    batchProgress: (completed: number, total: number, currentBatch: number, batches: number) =>
      `${completed}/${total} signals · batch ${currentBatch}/${batches}`,
    signalTypeLegendSummary: 'Signal-type legend',
    signalTypeLegendFooter:
      "Names and high-level meanings are from GMGNAI's official gmgn-skills CLI documentation. GMGN does not publish every wallet-classification, amount, count, or time-window threshold here, so these labels are observations—not quality or profitability verdicts.",
    signalTypeLabel: 'Signal type',
    allTypes: 'All types',
    capturedSignalsInFilter: (count: number, plural: string) =>
      `${count} captured signal${plural} in this filter`,
    chooseSignalTypeIntro:
      'Choose a signal type, then measure all matching signals. The app submits Dune-safe batches, skips complete outcomes, and retries only signals that are eligible for another measurement.',
    stopAfterCurrentBatchTitle: 'Finish the current batch, then stop submitting new Dune batches.',
    stopAfterCurrentBatch: 'Stop after current batch',
    newSignalsReady: 'new signals ready',
    neverMeasuredSelected: (count: number) =>
      `Never measured. Selected for the next safe Dune pass: ${count}.`,
    measuring: 'Measuring…',
    measureNew: (count: number) => `Measure new (${count})`,
    readyToRefetch: 'ready to re-fetch',
    retryQueueDetail: (neverMaturelyAttempted: number, retryEligibleSelected: number) =>
      `Earlier data was incomplete or unavailable, and its retry delay has elapsed (${neverMaturelyAttempted} of these get their first fair post-buffer check). Screened retry queue: ${retryEligibleSelected}. Requests are sent in small batches.`,
    refetching: 'Re-fetching…',
    refetchMatured: (count: number) => `Re-fetch matured (${count})`,
    waitingNothingToDo: 'waiting — nothing to do yet',
    waitingDetail: (
      pending: number,
      tooFresh: number,
      bufferHours: number,
      waitingOnRetryBuffer: number,
    ) =>
      `${pending} waiting on a checkpoint time · ${tooFresh} never measured, still inside the ${bufferHours}h buffer · ${waitingOnRetryBuffer} already measured, waiting to turn ${bufferHours}h old or for its retry delay before another attempt. All move into the queues above automatically; nothing runs on its own.`,
    reconcileTitle:
      "Checks stuck Dune runs against Dune's real current state and finalizes any that have actually finished, without re-submitting them.",
    reconciling: 'Reconciling…',
    reconcileInFlight: (count: number, plural: string) =>
      `Reconcile ${count} in-flight signal${plural}`,
    howThisPassWorks: 'How this Dune pass works',
    signalsReviewed: (count: number) => `${count} stored signals reviewed; nothing was deleted`,
    onlyNextSafeBatch:
      'The app sends only the next safe batch to Dune. Everything else stays in SQLite and can be reconsidered later.',
    whySignalsInOrOut: 'Why these signals are in or out of this Dune pass',
    candidatesEvaluated: (count: number) =>
      `${count} stored candidates evaluated; nothing was deleted.`,
    selectedCount: (count: number, percent: string) => `${count} selected (${percent})`,
    coreAuditExplanation:
      'Core = first token/type observation; audit = deterministic sample of deferred rows.',
    deferredRepeatsCount: (count: number, percent: string) =>
      `${count} deferred repeats (${percent})`,
    deferredRepeatsExplanation:
      'Later observation of a token/type whose lifetime-first row is already the research unit.',
    deferredByBudgetCount: (count: number, percent: string) =>
      `${count} deferred by budget (${percent})`,
    deferredByBudgetExplanation: (maxSignalIds: number) =>
      `Valid lifetime-first rows waiting because this pass allows ${maxSignalIds} total requests.`,
    waitingForBufferCount: (count: number, hours: number, percent: string) =>
      `${count} waiting for ${hours}h buffer (${percent})`,
    waitingForBufferExplanation:
      'Never measured; younger than the required observation buffer before its first Dune request. Not a rejection — it will become eligible automatically once old enough.',
    alreadyMeasuredCount: (count: number, percent: string) =>
      `${count} already measured (${percent})`,
    alreadyMeasuredExplanation:
      'Has a completed/pending/in-flight/retry-protected Dune outcome; it is not submitted again now.',
    invalidCount: (count: number, percent: string) => `${count} invalid (${percent})`,
    invalidExplanation:
      'Missing required token address, signal type, UTC observation time, or capture date.',
    completeOutcomes: 'complete outcomes',
    readyToRefetchShort: 'ready to re-fetch',
    notComplete: 'not complete',
    stuckUseReconcile: (count: number) => `${count} stuck (use Reconcile above)`,
    upToDateSuffix: ' — up to date',
    measurementDetailsSummary: 'Measurement details',
    gmgnParsing: 'GMGN parsing',
    complete: 'COMPLETE',
    normalizedSignalsStored: (count: number) => `${count} normalized signals stored`,
    latestCapture: (time: string) => `latest capture ${time}`,
    duneOutcomes: 'Dune outcomes',
    partial: 'PARTIAL',
    outcomesSummary: (measured: number, retryEligible: number, waiting: number) =>
      `${measured} complete outcomes · ${retryEligible} ready to re-fetch · ${waiting} waiting`,
    lastCompletedRun: (time: string) => `last completed run ${time}`,
    nextDuneWork: 'Next Dune work',
    upToDate: 'UP TO DATE',
    inFlight: 'IN FLIGHT',
    waiting: 'WAITING',
    pending: 'PENDING',
    nextWorkSummary: (newCount: number, retries: number, total: number) =>
      `${newCount} new · ${retries} retries · ${total} total selected`,
    nextWorkTiming: (pending: number, complete: number, inFlight: number) =>
      `${pending} waiting for target time · ${complete} complete · ${inFlight} in flight`,
    prescreenSummary: (core: number, audit: number, deferred: number, waiting: number) =>
      `Pre-screen: ${core} core · ${audit} audit · ${deferred} deferred · ${waiting} waiting for buffer`,
    batchRunInProgress: 'Batch run in progress',
    batchRunComplete: 'Batch run complete',
    batchProgressDetail: (
      completed: number,
      total: number,
      currentBatch: number,
      batches: number,
    ) =>
      `${completed}/${total} signals · batch ${currentBatch}/${batches}. Each batch is saved independently.`,
    signalHeader: (id: number, signalType: string) => `Signal #${id} · ${signalType}`,
    unknownSignalTypeShort: 'unknown',
    notAvailable: 'not available',
    checkpointStatus: (status: string, httpStatus: string | number) =>
      `${status} · HTTP ${httpStatus}`,
    missingCheckpointsNote: 'Missing checkpoints remain missing, never treated as zero.',
    outcomeColumnSignal: 'Signal',
    outcomeColumnType: 'Type',
    outcomeColumnChange: (label: string) => `${label} change`,
    outcomeColumnToken: 'Token',
    outcomeIntro:
      'Select one or more captured signals. The Dune SQL query uses supported time arithmetic for the signal time and its configured historical checkpoints. A checkpoint whose window has not yet elapsed shows as pending; a token with no matching trade remains unavailable.',
    copyTokenAddress: (address: string) => `Copy address ${address}`,
    noStuckRunsToReconcile: 'No stuck Dune runs to reconcile.',
    reconciled: (
      checked: number,
      completed: number,
      failed: number,
      stillRunning: number,
      noApiKey: number,
    ) =>
      `Reconciled ${checked} stuck run${checked === 1 ? '' : 's'}: ${completed} completed, ${failed} failed, ${stillRunning} still running${noApiKey ? ' (stopped early: no Dune API key configured)' : ''}.`,
    noMaturedOutcomesToRetry:
      'No matured outcomes are ready for re-fetch in this pass. Fresh checkpoints remain protected until their target time and retry delay have elapsed.',
    noNeverMeasuredSignals:
      'No never-measured signals are ready in this pass. New signals may still be waiting for a safe pre-screen slot.',
    noSignalsEligible:
      'No signals are currently eligible for measurement. Pending, unavailable, and already usable checkpoints are protected from unnecessary Dune requests.',
    batchMeasured: (batchNumber: number, totalBatches: number, batchSize: number) =>
      `Measured batch ${batchNumber} of ${totalBatches} (${batchSize} signals archived).`,
    batchFailed: (batchNumber: number, totalBatches: number, reason: string) =>
      `Batch ${batchNumber} of ${totalBatches} failed: ${reason} — continuing with the remaining batches.`,
    measuredWithFailures: (
      measured: number,
      total: number,
      totalBatches: number,
      failedCount: number,
      failedList: string,
    ) =>
      `Measured ${measured} of ${total} signals across ${totalBatches} batches; ${failedCount} batch${failedCount === 1 ? '' : 'es'} failed and ${failedCount === 1 ? 'was' : 'were'} skipped: ${failedList}. Completed batches remain saved — a stuck batch will be picked up automatically by reconciliation on the next run.`,
    measuredComplete: (reasonLabel: string, count: number, totalBatches: number) =>
      `${reasonLabel} ${count} signals in ${totalBatches} archived Dune batches. Existing complete measurements were skipped.`,
    measuredReasonLabels: { retry: 'Re-fetched', new: 'Measured new', all: 'Measured' },
    stoppedAfter: (measured: number, total: number, remaining: number) =>
      `Stopped after ${measured} of ${total} signals. Completed batches remain saved; the remaining ${remaining} signals can be run later.`,
    stopBatchRequested:
      'Stop requested. The current Dune batch will finish, then no further batches will be submitted.',
  },
  header: {
    eyebrow: 'GMGN / DUNE · BACKTEST',
    title: 'GMGN/Dune Backtest',
    lede: 'Find promising Solana wallets by comparing GMGN performance with realistic delayed-copy backtests.',
    themeLight: 'Light mode',
    themeDark: 'Dark mode',
    sectionsAriaLabel: 'Research sections',
    navWalletStats: 'Wallet Data',
    navPatternDiscovery: 'Pattern Research',
    navApiReference: 'API Docs',
    navDecisionLab: 'Decision Engine',
    signalWorkspaceAriaLabel: 'Signal workspace',
    signalLabel: 'Signal',
    navImports: 'Imports',
    navGmgnCapture: 'GMGN Capture',
    navDuneCapture: 'Dune Capture',
    navPatterns: 'Patterns',
  },
  overview: {
    importCohort: 'Import a Dune cohort',
    notStarted: 'Not started',
    tokensStored: (count: string) => `${count} tokens stored`,
    captureGmgnSignals: 'Capture GMGN signals',
    signalsCaptured: (count: string) => `${count} signals captured`,
    importOrWatch: 'Import a browser export, fetch once, or start watching',
    reviewEvidence: 'Review evidence & diagnostics',
    archivesCoverageActivity: 'Archives, coverage, activity, and logs below',
    tokensLabel: 'Tokens',
    uniqueAddresses: 'unique addresses',
    gmgnSignalsLabel: 'GMGN signals',
    rawObservations: 'raw observations',
    firstTradeRange: 'First trade range',
    to: (value: string) => `to ${value}`,
    observedRange: 'Observed range',
  },
  walletStats: {
    fetchAlreadyRunningResuming: 'A CopyTrade fetch is already running. Resuming its progress.',
    fetchStarted: (runId: number | string) => `CopyTrade fetch started (run ${runId}).`,
    fetchingTradesFor: (label: string, runId: number | string) =>
      `Fetching trades for ${label} (run ${runId}).`,
    fetchingTradesForWinners: (runId: number | string) =>
      `Fetching trades for the current Winners (run ${runId}).`,
    stopRequested: (runId: number | string | null | undefined) =>
      `Stop requested for CopyTrade fetch${runId ? ` (run ${runId})` : ''}. The current request will finish, then the run will stop.`,
    noFetchWasRunning: 'No CopyTrade fetch was running.',
    resumedFetch: (runId: number | string) => `Resumed GMGN top-100 fetch (run ${runId}).`,
    resumeSnapshotReset: 'GMGN resume snapshot reset. Saved trades were kept.',
    noSnapshotToReset: 'No GMGN snapshot to reset.',
    importedWallets: (count: number, fileName: string) =>
      `Imported ${count} GMGN wallets from ${fileName}. No live GMGN request was made.`,
    fetchingHistoryForImportedTop100: 'Fetching GMGN history for the imported top 100…',
    gmgnHistoryComplete: 'GMGN history complete. Review the saved screening result.',
    gmgnHistoryStatus: (status: string) => `GMGN history ${status}. Saved progress is retained.`,
    gmgnHistoryStopped: (message: string) => `GMGN history stopped: ${message}`,
    importedWalletTrades: (
      imported: number,
      fileName: string,
      duplicates: number,
      malformed: number,
    ) =>
      `Imported ${imported} wallet trades from ${fileName}; ${duplicates} duplicates retained as history. ${malformed} malformed rows were kept in the raw archive.`,
    snapshotSaved: (snapshotId: number) => `CopyTrade snapshot #${snapshotId} saved.`,
    openingSavedDetails: (wallet: string) => `Opening saved details for ${wallet}`,
    eyebrow: '30-DAY COHORT · 30-DAY DECISION',
    title: 'Who is worth following?',
    tag: '30D DECISION VIEW',
    loadingEvidence: 'Loading saved trader evidence…',
    loadingEvidenceDetail:
      'Reading the roster, GMGN summaries, Dune results, and consistency report from SQLite. Decisions stay hidden until every required report finishes.',
    evidenceCouldNotBeLoaded: 'Decision evidence could not be loaded',
    noTemporaryVerdicts: (error: string) => `${error} No temporary verdicts are shown.`,
    retrySavedEvidence: 'Retry saved evidence',
    showingPositiveCopyRows: 'Showing positive-copy rows · ',
    gmgnSummariesFresh: (fresh: number, total: number) => `GMGN summaries: ${fresh}/${total} fresh`,
    fetchedAt: (time: string) => ` (${time})`,
    notCompletedParens: ' (not completed)',
    duneLabel: 'Dune:',
    duneStatusComplete: 'complete',
    duneStatusPartial: 'partial',
    duneStatusNotCompleted: 'not completed',
    thirtyDayPeriodSuffix: ' · 30-day period',
    fetchControls: 'Fetch controls',
    fetchControlsDetail: 'Update saved GMGN history first, then run the Dune copy test.',
    step0Title:
      'Runs before step 1 — this only narrows which wallets steps 1 and 2 will touch, it fetches nothing itself.',
    narrowDuneScopeFirst: 'Narrow the Dune scope first',
    narrowDuneScopeDetail:
      "Skips wallets Dune fetching can never help or shouldn't be spent on — see the checkbox tooltip for the full list of checks.",
    currentlyWalletCount: (count: number, plural: string) => ` Currently ${count} wallet${plural}.`,
    scopeFilterTooltip: (
      delaySeconds: number,
      uncopyableCount: number,
      uncopyablePlural: string,
      highRiskCount: number,
      highRiskPlural: string,
    ) =>
      `Two kinds of check, both from data already on hand — no new Dune or GMGN request:\n\n• Can't be copied: median hold time < the ${delaySeconds}s copy delay. Not a judgment call — the verdict already forces "Not copyable" for this regardless of what Dune returns, so spending credits on it is provably wasted (${uncopyableCount} wallet${uncopyablePlural}).\n\n• GMGN-flagged high-risk: wash_trader tag, 30d PnL ≤ -20%, >5,000 trades in 30d, >100 tokens created, <10 trades in 30d, <20% win rate, or >90% one-sided buy/sell activity. These ARE judgment calls, not provable waste — a legitimate trader could still trip one (${highRiskCount} wallet${highRiskPlural}).\n\nOverride any individual wallet in the activity table below regardless of which check it hit.`,
    skipLowValueWallets: 'Skip low-value wallets (uncopyable or GMGN-flagged high-risk)',
    countParens: (count: number) => ` (${count})`,
    staleDataTitle:
      "Estimate only, from each wallet's own historical average trade rate over its stored 30-day window — not a live check. A quiet wallet can still trade any minute; a busy one can go silent for days. The one certain number here is how long ago the data was last confirmed current.",
    staleDataMessagePrefix: 'Your GMGN data is',
    staleDataOld: (duration: string) => `${duration} old`,
    staleDataLastFetched: (time: string) => `(last fetched ${time}).`,
    staleDataEstimatePrefix: "Based on this cohort's historical trading pace, an estimated",
    staleDataEstimateTrades: (count: string) => `~${count} trades`,
    staleDataEstimateSuffix: 'may',
    staleDataEstimateEnd:
      "have happened since then that this view does not yet reflect. Skip fetching only if that's a risk you're fine carrying.",
    preparingResearch: 'Preparing research…',
    existingResponsesRetained:
      'Existing GMGN and Dune responses are retained; only missing work is requested.',
    gmgnSummariesLabel: 'GMGN summaries',
    gmgnSummariesProgress: (done: number, total: number, requests: number) =>
      `${done} / ${total} wallets · ${requests} requests`,
    fetchingAndParsing: 'Fetching and parsing wallet statistics',
    duneCopyPrices: 'Dune copy prices',
    duneCopyPricesQuery: (
      currentBatch: number | string,
      batchesTotal: number | string,
      processed: string,
      total: string,
    ) => `Query ${currentBatch} / ${batchesTotal} · ${processed} / ${total} targets`,
    duneCopyPricesDetail: (stored: string, failed: string, remaining: string, state: string) =>
      `${stored} stored · ${failed} failed · ${remaining} remaining · Dune ${state}`,
    submitting: 'submitting',
    gmgnScreening: 'GMGN screening',
    walletsFetchedAt: (statsCount: number, total: number, time: string) =>
      `${statsCount}/${total} wallets · fetched ${time}`,
    noSavedScreeningYet: 'No saved screening yet',
    compareTop100Title: 'Compare the current GMGN top 100 with the previous saved list',
    openTop100ComparisonAriaLabel: 'Open GMGN top 100 comparison',
    fetching: 'Fetching…',
    savedScreeningAvailable: 'Saved screening available',
    notFetched: 'Not fetched',
    completeWalletHistorySummaries: 'Complete wallet history and 30-day summaries',
    walletsProgress: (done: number, total: number) => `${done}/${total} wallets`,
    progressCalculating: 'Progress calculating',
    currentWallet: (address: string) => `Current: ${address}`,
    preparingWallet: 'Preparing wallet',
    rosterFetchProgressDetail: (
      stored: string,
      newCount: string,
      duplicates: string,
      requests: string,
    ) => `${stored} stored · ${newCount} new · ${duplicates} duplicates · ${requests} requests`,
    walletEtaCalculating: 'Wallet ETA calculating',
    currentWalletRemaining: (time: string) => `${time} current wallet remaining`,
    totalEtaCalculating: 'Total ETA calculating',
    totalRemaining: (time: string) => `${time} total remaining`,
    failedWalletsDetail: (failed: string, walletEta: string, totalEta: string) =>
      `${failed} failed wallets · ${walletEta} · ${totalEta}`,
    pausing: 'Pausing…',
    pauseGmgnFetch: 'Pause GMGN fetch',
    resuming: 'Resuming…',
    resumeGmgnFetch: 'Resume GMGN fetch',
    importTop100Title:
      'Import a GMGN leaderboard JSON file or Chrome extension export. This does not call GMGN.',
    importing: 'Importing…',
    importTop100Json: 'Import top 100 JSON',
    fetchImportedHistoryTitle:
      'Fetch GMGN trade history and 30-day summaries for the imported roster. The leaderboard itself is never fetched by this button.',
    fetchingHistory: 'Fetching history…',
    fetchImportedGmgnHistoryButton: 'Fetch imported GMGN history',
    liveLeaderboardDisabledNote:
      'Live GMGN leaderboard fetching is disabled here. Upload the JSON response directly or export a Chrome extension capture containing the leaderboard request.',
    forgetCursorTitle: 'Forget only the resumable cursor. Saved GMGN trades remain in SQLite.',
    resetting: 'Resetting…',
    resetResumeSnapshot: 'Reset resume snapshot',
    liveRefreshBlockedPrefix: 'Live refresh blocked',
    walletsCount: (statsCount: number, total: number) => `${statsCount}/${total}`,
    walletsSuffix: 'wallets',
    notFastFastCounts: (notFast: number, fast: number) => `${notFast} not fast · ${fast} fast`,
    tradesCount: (trades: string, periodDays: number) => `${trades} trades · ${periodDays}d`,
    mostActive: 'Most active:',
    mostActiveWallet: (address: string) => ` · ${address}`,
    selectedForDune: 'selected for Dune',
    excludedCount: 'excluded',
    excludedByTriage: (count: number) => ` (${count} by triage)`,
    skipsRejectedTriageTooltip: (count: number) =>
      `Skips the ${count} wallets rejected by the current triage run. Uncheck to include them, or re-check an individual row below.`,
    runTriageFirstTooltip:
      'Run triage after the latest GMGN and Dune fetches before using its exclusions.',
    skipWalletsTriageRejected: 'Skip wallets triage rejected',
    triageOutOfDate: ' · triage out of date',
    showActivityTable: (count: number) => `Show activity table (${count})`,
    selectedForDuneYellowRows: 'selected for Dune · yellow rows have Dune data to fetch',
    selectAll: 'Select all',
    deselectAll: 'Deselect all',
    columnFetch: 'Fetch?',
    columnActivityNumber: 'Activity #',
    columnRank: 'Rank',
    columnTrader: 'Trader',
    columnTrades: 'Trades',
    columnNetProfit30d: 'Net profit (30d)',
    columnDelayFit: 'Delay fit',
    unknown: 'Unknown',
    poorFitFastTrader: 'Poor fit — fast trader',
    betterFitFetch: 'Better fit — fetch',
    includeExcludeInDune: (action: string, name: string) => `${action} ${name} in Dune research`,
    include: 'Include',
    exclude: 'Exclude',
    needsMoreEvidence: 'Needs more evidence',
    rejectedByTriageTooltip:
      'The last triage run rejected this wallet. Check the box to fetch it anyway.',
    rejectedByTriage: ' · rejected by triage',
    checkBoxToFetchAnyway: 'Check the box to fetch it anyway.',
    noHoldTimeData: 'No hold-time data',
    averageHold: (time: string) => `${time} average hold`,
    holdTimeProxyTitle: (evidenceReason: string) =>
      `GMGN provides average holding time here; this is the best available delay-risk proxy.\n\n${evidenceReason}`,
    summariesMissing: (count: number) => `${count} summaries missing`,
    duneCopyTest: 'Dune copy test',
    lastFetched: (time: string) => `Last fetched ${time}`,
    noSavedDuneRunYet: 'No saved Dune run yet',
    processingDuneTargets: 'Processing Dune targets…',
    duneCompleteNoNewTargets: 'Dune complete · no new targets',
    duneRunComplete: 'Dune run complete',
    savedDuneEvidenceAvailable: 'Saved Dune evidence available',
    targetsProcessedDetail: (processed: string, total: string, remaining: string) =>
      `${processed} / ${total} targets processed · ${remaining} remaining`,
    walletsNeedMoreEvidence: (count: number, targetsDetail: string) =>
      `${count} wallets need more evidence; ${targetsDetail}`,
    duneTargetCountLoading: 'Dune target count is loading',
    priceTargetsRemain: (count: string) => `${count} price targets remain`,
    stopping: 'Stopping…',
    stopDuneFetch: 'Stop Dune fetch',
    noNewDuneDataToFetch: 'No new Dune data to fetch',
    resumeDune: (targets: string, wallets: number) =>
      `Resume Dune (${targets} targets · ${wallets} wallets)`,
    fetchDuneTargets: (targets: string, wallets: number) =>
      `Fetch ${targets} Dune targets (${wallets} wallets)`,
    duneResearchScope: 'Dune research scope',
    walletsStillNeedData: (count: number) => `${count} wallets still need more data`,
    selectedWallets: 'selected wallets',
    needMoreEvidence: 'need more evidence',
    haveSavedDuneResult: 'have a saved Dune result',
    priceTargetsUnqueried: 'price targets unqueried',
    queriedNoUsableMatch: 'queried with no usable match',
    targetsRemainingFailed: (processed: string, total: string, remaining: string, failed: string) =>
      `${processed} / ${total} targets · ${remaining} remaining · ${failed} failed`,
    lastAuditedRun: (
      planned: string,
      submitted: string,
      stored: string,
      failed: string,
      remaining: string,
    ) =>
      `Last audited run: planned ${planned} · submitted ${submitted} · stored ${stored} · failed ${failed} · remaining ${remaining}`,
    stillFailEvidenceRule: (count: number) =>
      `These ${count} wallets still fail a decision-evidence rule, but Dune has no unqueried prices left. The missing evidence may be insufficient sample/coverage or a price Dune could not match; another normal fetch cannot create it.`,
    buttonTargetsOnlyThese: (count: number, otherCount: number) =>
      `The button above targets only these ${count} wallets. It fetches their missing eligible price targets and keeps completed results; it does not fetch the other ${otherCount} wallets.`,
    noSelectedWalletNeedsEvidence:
      'No selected wallet currently needs more evidence; the Dune button is disabled.',
    duneReportedSingle: 'Dune reported: ',
    duneReportedMultiple: (count: number) => `Dune reported ${count} distinct errors: `,
    gmgnRosterComparisonAriaLabel: 'GMGN top 100 comparison',
    gmgnRosterEyebrow: 'GMGN ROSTER',
    top100Comparison: 'Top 100 wallet comparison',
    currentCapturedAt: (time: string) => `Current: ${time}`,
    noSavedSnapshot: 'No saved snapshot',
    close: 'Close',
    noEarlierGmgnList:
      'No earlier GMGN list is saved, so there is no baseline for identifying new or departed wallets.',
    newToday: (count: number) => `${count} new today`,
    leftPreviousList: (count: number) => `${count} left the previous list`,
    leftTheList: 'Left the list',
    none: 'None.',
    currentRankedList: 'Current ranked list',
    columnWallet: 'Wallet',
    columnGmgn30dPnl: 'GMGN 30d PnL',
    columnStatus: 'Status',
    newTodayBadge: 'NEW TODAY',
    previouslyListed: 'Previously listed',
    exportingCsvDetails: 'Exporting CSV + details…',
    exportTableDetails: 'Export table + details',
    walletsSelectedForDune: (count: number) => `${count} wallets selected for Dune`,
    gmgnRosterSourceLive: 'GMGN roster source: live request',
    gmgnRosterSourceSaved: 'GMGN roster source: saved snapshot',
    joinedLeftUnchanged: (joined: number, left: number) =>
      `${joined} joined · ${left} left · unchanged wallets remain in the saved history.`,
    noNewLeaderboardReceived:
      'No new leaderboard was received, so no membership change was measured.',
    showWalletChanges: 'Show wallet changes',
    joined: 'Joined',
    left: 'Left',
    summariesFreshUsableTargets: (fresh: number, total: number, targets: string) =>
      `${fresh} / ${total} summaries fresh · ${targets} usable Dune target legs`,
    showPositiveCopyGainsOnly: 'Show positive copy gains only',
    waitingForEvidence: 'Waiting for evidence',
    rowsShown: (count: number) => `${count} shown`,
    columnsSummary: 'Columns',
    decisionEvidenceUnavailable:
      'Decision evidence is unavailable. Retry the saved evidence read above.',
    loadingSavedDecisionEvidence: 'Loading saved decision evidence…',
    loadRosterToBuildCandidates:
      'Load a roster and fetch GMGN summaries to build the candidate list.',
    duneMatchRecoveryEyebrow: 'DUNE MATCH RECOVERY',
    gmgnRank: (rank: string) => `GMGN rank ${rank}`,
    widenDuneSearchWindowAriaLabel: 'Widen Dune search window',
    allLegsQueriedNote:
      "All current trade legs have already been queried, but some returned no usable price. This targeted retry searches only this wallet's no-match legs with a wider time window.",
    currentUsableCoverage: 'Current usable coverage',
    matchedRoundTrips: 'Matched round trips',
    estimatedRetryLegs: 'Estimated retry legs',
    estimatedDuneQueries: 'Estimated Dune queries',
    coverageResultUnavailable: 'Coverage result unavailable',
    coverageIncreased: (before: string, after: string, delta: string) =>
      `Coverage increased ${before}% → ${after}% (+${delta} percentage points)`,
    coverageUnchanged: (percent: string) => `Coverage unchanged at ${percent}%`,
    coverageChanged: (before: string, after: string) => `Coverage changed ${before}% → ${after}%`,
    duneConfirmedRetryLegs: (submitted: string) =>
      `Dune confirmed this after storing ${submitted} retry legs. The table was reloaded from the saved matches.`,
    widerSearchWindow: 'Wider search window',
    window15Minutes: '15 minutes · first recovery step',
    window30Minutes: '30 minutes · medium cost',
    window60Minutes: '60 minutes · higher cost',
    window120Minutes: '120 minutes · last resort',
    duneNoCreditEstimateNote:
      'Dune does not provide a reliable credit estimate before execution. The leg count and query count above are the budget preview; longer windows may scan more data. Start with 15 minutes and expand only if coverage improves.',
    retryLegsProgress: (processed: string, total: string) => `${processed} / ${total} retry legs`,
    retryLegsDetail: (stored: string, failed: string, remaining: string) =>
      `${stored} stored · ${failed} failed · ${remaining} remaining`,
    fetchingWiderPrices: 'Fetching wider prices…',
    fetchMissingLegs: (count: string) => `Fetch ${count} missing legs`,
    traderEvidenceSummary: 'Trader evidence',
    bucketLostOver50: 'Lost over 50%',
    bucketLost0to50: 'Lost 0-50%',
    bucketGain0to2x: 'Gained 0-2x',
    bucketGain2to5x: 'Gained 2-5x',
    bucketGainOver5x: 'Gained over 5x',
    tradePointLabel: (trade: number) => `Trade ${trade}`,
    startLabel: 'Start',
    columnPnl1d: '1d PnL',
    columnPnl7d: '7d PnL',
    columnPnl30d: '30d PnL',
    columnWin7d: '7d win',
    columnWin30d: '30d win',
    columnTrades7d: 'Trades 7d',
    columnTrades30d: 'Trades 30d',
    columnMedianHold: 'Median hold',
    columnDelayHold: (seconds: number) => `${seconds}s delay / hold`,
    columnCopyTest: '30d copy test',
    columnDuneCoverage: 'Dune coverage',
    noDuneResult: 'No Dune result',
    columnReading: 'Reading',
    noDelayEvidence: 'No delay evidence',
    survived: '✓ survived',
    tradeDetailsFor: (name: string) => `Trade details for ${name}`,
    roundTripAuditEyebrow: 'ROUND-TRIP AUDIT',
    eachRowRoundTrip: (delaySeconds: number) =>
      `Each row is one stored buy→sell round trip. Copy result uses the configured ${delaySeconds}s delay, Dune-matched prices, fees, and slippage. Opening this dialog reads SQLite only.`,
    noSimulationStored:
      'No simulation report is stored for this wallet yet. Fetch missing Dune prices first.',
    roundTripsStored: 'round trips stored',
    copySimulations: 'copy simulations',
    missingDuneMatches: 'missing Dune matches',
    coverage: 'coverage',
    heldTimeRange: (buyAt: string, sellAt: string) => `${buyAt} → ${sellAt}`,
    columnWalletReturn: 'Wallet',
    columnCopied: 'Copied',
    columnEdgeKept: 'Edge kept',
    columnEntryExitLag: 'Entry / exit lag',
    columnRawStatus: 'Status',
    matchStatusTitle: (entry: string, exit: string) => `${entry} · ${exit}`,
    noEntryMatch: 'no entry match',
    noExitMatch: 'no exit match',
    gmgnSavedStatisticsFor: (title: string) => `GMGN saved statistics for ${title}`,
    gmgnSavedResponseEyebrow: 'GMGN SAVED RESPONSE',
    // Checklist wording below intentionally mirrors decisionEngine.ts's decideThirtyDayVerdict /
    // explainThirtyDayDecision gates verbatim (see progress.md 2026-08-23 "Improved legacy
    // Decision Lab explanations" / "Relabeled the tile and tooltip..." entries) — do not reword.
    checklistGmgn30dPositive: '30-day GMGN result positive',
    checklistDelayedCopySurvived: 'Delayed-copy portfolio survived fees, slippage, delay, and gas',
    checklistDelayedCopyMedianPositive: 'Median copied trade positive (not just the total)',
    checklistHistoricalConsistency:
      'Historical consistency: earlier and recent halves both positive',
    checklistLoading: 'Loading…',
    checklistNotEnoughData: 'Not enough data',
    checklistDeclining: 'Declining (recent half worse than earlier half)',
    checklistRecentOnly: 'Only the recent half is positive',
    checklistConsistentlyNegative: 'Consistently negative',
    checklistConsistent: 'Consistent',
    checklistNoLosingWeek: 'No losing week',
    checklistWeeksMeasured: (measured: number, minimum: number) =>
      `${measured}/${minimum} weeks measured, every week's median must be positive`,
    decisionLabel: 'Decision',
    sevenDayHistory: '7-day history',
    delayedCopyResult: 'Delayed copy result',
    duneEvidence: 'Dune evidence',
    notMeasured: 'Not measured',
    usablePercent: (percent: string) => `${percent}% usable`,
    verdictPassedGates:
      'This row passed the current historical, coverage, freshness, and delayed-copy gates.',
    verdictNeedsDataNote: 'This trader is not rejected; the evidence is incomplete or stale.',
    verdictNotCopyableNote: 'The typical holding time is shorter than the configured copy delay.',
    verdictOtherNote:
      'This is a historical or data-quality result, not a final follow recommendation.',
    hundredDollarPathLabel: '$100 after-copy path',
    hundredDollarPathTip:
      'The simulated cash balance after each completed copied trade, using the configured delay, fees, slippage, gas, fixed $10 stake, and position limit. Older saved runs may show one point per day until they are recomputed.',
    completedTrades: (count: number) => `${count} completed trades`,
    savedDailyPath: 'Saved daily path',
    scrollToZoomHint: 'Scroll over chart to zoom',
    tradeReconciliation: 'Trade reconciliation',
    chartTableCounts: (chart: number, table: number) => `Chart: ${chart} · Table: ${table} sells`,
    chartPredatesTradeIds:
      'This saved chart predates trade IDs, so its points cannot be matched row-by-row.',
    everyRowMatchesChartPoint: 'Every visible sell row has a matching chart point.',
    missingRowsAndPoints: (
      rowCount: number,
      rowPlural: string,
      pointCount: number,
      pointPlural: string,
    ) =>
      `${rowCount} table row${rowPlural} missing from chart · ${pointCount} chart point${pointPlural} missing from table.`,
    partialSellsNote:
      ' Partial sells split the fixed stake proportionally; open positions remain valued at cost until sold.',
    gmgnPeriodResultsEyebrow: 'GMGN PERIOD RESULTS',
    sevenDayLabel: '7-day',
    thirtyDayLabel: '30-day',
    realizedPnl: 'Realized PnL',
    profit: 'Profit',
    winRate: 'Win rate',
    buysSells: 'Buys / sells',
    tokens: 'Tokens',
    averageHoldPeriodLabel: 'Average hold',
    periodFetchedAt: (time: string) => `Fetched ${time}`,
    noGmgnStatsSaved:
      'No GMGN statistics response has been saved for this trader yet. Run "Fetch missing stats".',
    periodLabel: 'Period',
    fetchedLabel: 'Fetched',
    twitterLabel: 'Twitter',
    walletCreatedLabel: 'Wallet created',
    realizedProfitLabel: 'Realized profit',
    returnOnCost: 'Return on cost',
    avgHoldGmgn: 'Avg hold (GMGN)',
    storedSellHistoryLabel: 'Stored sell history',
    storedSellHistoryTip:
      'Only sell rows are shown here. They are the rows that close positions and provide realized results; the underlying buy rows remain saved in SQLite for matching and audit.',
    loadingEllipsis: 'Loading…',
    sellsCount: (count: string) => `${count} sells`,
    onlyShowSellsFromWindow: (days: number) =>
      `Only show sells from the current ${days}-day window`,
    loadingSavedTrades: 'Loading saved trades…',
    columnHash: '#',
    columnSellTime: 'Sell time',
    columnToken: 'Token',
    columnHeld: 'Held',
    columnPnl: 'P/L',
    realizedReturnTitle: 'Realized return using the stored sell proceeds and buy cost basis',
    columnTransaction: 'Transaction',
    noStoredSellRows: 'No stored sell rows for this wallet.',
    noStoredTradeRows: 'No stored trade rows for this wallet.',
    historyNote1:
      'This shows the sell rows available locally. The coverage note below explains if the original provider response was capped or interrupted.',
    historyNote2:
      'Only stored sell rows are shown because they close a position and provide the realized result. Hold is matched to the earlier stored buy for the same token; "—" means that buy row was not saved.',
    fetchRecord: (requests: number, truncated: string, stopReason: string, updatedAt: string) =>
      `Fetch record: ${requests} provider requests · ${truncated}${stopReason} · saved ${updatedAt}`,
    historyWasTruncated: 'history was truncated',
    fetchNotMarkedTruncated: 'fetch was not marked truncated',
    stopReasonSuffix: (reason: string) => ` · ${reason}`,
    outcomeDistributionLabel: 'Outcome distribution',
    outcomeDistributionTip:
      "GMGN's own count of positions by result. This is the closest thing the aggregate endpoint gives to a return histogram — it shows whether gains come from many small wins or a few large ones.",
    positionsCounted: (count: string) => `${count} positions counted`,
    distinctTokensTraded: (count: string) => ` · ${count} distinct tokens traded`,
    flowAndCostsLabel: 'Flow and costs',
    flowAndCostsTip:
      'Gross amounts GMGN reports for this window. Fees are already reflected in realized profit; they are shown separately so their size is visible.',
    buysLabel: 'Buys',
    sellsLabel: 'Sells',
    boughtCost: 'Bought cost',
    soldIncome: 'Sold income',
    buyFees: 'Buy fees',
    sellFees: 'Sell fees',
    solBalance: 'SOL balance',
    lastActivity: 'Last activity',
    everyValueOwnReportedFigure:
      "Every value here is GMGN's own reported figure for this wallet, saved as-is. It describes what the trader did — not what copying them would have returned.",
    openSavedWalletDetailsTitle: 'Open saved wallet and trade details',
    contactingGmgnForTop100: 'Contacting GMGN for the current top 100…',
    noUsableLeaderboard: 'GMGN returned no usable wallet leaderboard; no roster was changed.',
    usedApprovedSavedSnapshot: (snapshotId: number, capturedAt: string, walletCount: number) =>
      `Used approved saved snapshot ${snapshotId} from ${capturedAt}: ${walletCount} wallets. No old data was overwritten.`,
    theLatestCapture: 'the latest capture',
    rosterRefreshSuccess: (
      walletCount: number,
      snapshotId: number,
      added: number,
      alreadyPresent: number,
    ) =>
      `Success: GMGN top ${walletCount} saved as snapshot ${snapshotId}. ${added} new wallet${added === 1 ? '' : 's'} · ${alreadyPresent} already known. Older snapshots were kept.`,
    liveFetchFailedConfirm:
      'Live GMGN top-100 fetch failed. Read the latest saved local snapshot instead?\n\nThis will not fetch new wallets.',
    refreshFailed: (message: string) =>
      `Refresh failed: ${message}. The previous roster was left unchanged.`,
    allWalletsExcluded:
      'All screened wallets are excluded. Re-enable at least one candidate before researching.',
    fetchingMissingDunePrices: 'Fetching missing Dune prices…',
    refreshingDecisionTable: 'Refreshing the decision table…',
    researchUpdateComplete:
      'Research update complete. Saved evidence was reused; only missing or stale work was requested.',
    updateStopped: (message: string) => `Update stopped: ${message}`,
    workflowStepFailed: 'Failed; saved work was retained.',
    rosterSaved: 'Roster saved.',
    refreshingTop100Roster: 'Refreshing the top 100 roster…',
    waitingToSelectRoster: 'Waiting to select the roster.',
    gmgnHistoryProgress: (
      walletDone: number,
      walletTotal: number,
      tradesFetched: number,
      requestsMade: number,
    ) =>
      `${walletDone} / ${walletTotal} wallets · ${tradesFetched} new trades · ${requestsMade} requests`,
    gmgnHistoryWalletsComplete: (walletCount: number) =>
      `${walletCount} wallets complete · saved in SQLite.`,
    startingGmgnHistoryFetch: 'Starting the GMGN history fetch…',
    waitingForRosterStep: 'Waiting for the roster step.',
    gmgnSummaryProgress: (walletDone: number, walletTotal: number, requestsMade: number) =>
      `${walletDone} / ${walletTotal} wallets · ${requestsMade} requests`,
    gmgnSummaryComplete: (skippedExisting: number) =>
      `Complete · ${skippedExisting} saved summaries reused.`,
    startingGmgnSummaryFetch: 'Starting the GMGN summary fetch…',
    waitingForGmgnHistory: 'Waiting for GMGN history.',
    duneFetchProgress: (processed: number, total: number, remaining: number) =>
      `${processed} / ${total} Dune targets · ${remaining} remaining`,
    duneFetchComplete: (storedTargets: number) => `Complete · ${storedTargets} targets stored.`,
    startingDuneFetch: 'Starting the Dune fetch…',
    waitingForApprovalAndGmgnSummaries: 'Waiting for approval and GMGN summaries.',
    decisionTableRefreshed: 'Decision table refreshed.',
    recomputingDecisions: 'Recomputing decisions from saved evidence…',
    waitingForDuneResults: 'Waiting for Dune results.',
    decisionColumns: {
      rank: 'Rank',
      gmgn: 'GMGN',
      trader: 'Trader',
      decision: 'Decision',
      freshness: 'Data freshness',
      gmgnPnl: '30d GMGN PnL',
      gmgnTrades: '30d GMGN trades',
      copyMedian: '30d copy median',
      copyCapital: '$100 after copy',
      evidence: 'Evidence',
      duneCoverage: 'Dune coverage',
      hold: 'Typical hold',
      under15s: 'GMGN ≤15s trades',
      gmgnTags: 'GMGN tags',
    },
  },
  patternDiscovery: {
    historyUnavailable: (periodDays: number) =>
      `At least one wallet must have completed ${periodDays}d history before Pattern Research can run.`,
    historySubset: (coveredWallets: number, excludedWallets: number, periodDays: number) =>
      `Pattern Research will use ${coveredWallets} wallets with verified ${periodDays}d history; ${excludedWallets} incomplete wallets will be excluded.`,
    duneWalletSelection: {
      eyebrow: 'DUNE DIAGNOSTICS',
      title: 'Choose wallets to fetch',
      description:
        'Select the wallets whose delayed-copy evidence should be refreshed. No fetch starts until you confirm.',
      cancel: 'Cancel',
      selected: (selected: number, total: number) => `${selected} of ${total} wallets selected`,
      trades: (periodDays: number) => `GMGN trades (${periodDays}d)`,
      profitableOnly: (periodDays: number) =>
        `Select profitable wallets only (GMGN median return > 0% in ${periodDays}d)`,
      rank: 'Rank',
      wallet: 'Wallet',
      totalTrades: (periodDays: number) => `GMGN trades (${periodDays}d)`,
      profitability: (periodDays: number) => `GMGN profitability (${periodDays}d)`,
      loading: 'Loading GMGN trade counts…',
      empty: 'No GMGN wallet data is available. Load the GMGN roster first.',
      confirm: 'Fetch selected wallets',
    },
    summaryEyebrow: 'DISCOVERY SUMMARY',
    summaryTitle: 'What the run found',
    promotedPatterns: 'promoted patterns',
    stableCoverageLevels: 'coverage levels stable',
    highestUsefulCoverage: 'highest useful coverage',
    stableAtFullCoverage: 'stable patterns at 100%',
    strongestSignal: 'Strongest recurring signal:',
    strongestSignalText: 'high wallet activity → worse future copy returns.',
    coverageSensitivityTitle: 'Coverage sensitivity',
    coverageSensitivityHint: 'Click a coverage level to inspect its run details.',
    noEligibleData: 'No usable discovery data was available',
    noEligibleDataDetail:
      'Every coverage level was unavailable because no outcome-coverage rows met its requirements. No pattern was tested.',
    promoted: 'promoted',
    coverageDetailEvents: (wallets: string, rows: string, stable: number) =>
      `${wallets} wallets · ${rows} events · ${stable} stable patterns`,
    strictCoverageNote:
      'The strictest level has the smallest cohort. Zero stable patterns here does not invalidate patterns that repeat across wider coverage levels.',
    methodologyDiagnostics: 'Methodology and 100% diagnostics',
    validationSurvivorsAtFullCoverage: '100% validation survivors',
    discoveryRows: 'discovery rows',
    validationRows: 'validation rows',
    holdoutRows: 'untouched holdout rows',
    direction: 'Direction',
    strength: 'Strength',
    strong: 'Strong',
    medium: 'Medium',
    gridEyebrow: 'SHARED-GRID RESULT',
    gridTitle: 'What did the full discovery run learn?',
    gridStatus: (eligibleLevels: number, availableLevels: number): string =>
      eligibleLevels > 0
        ? `Validated patterns exist at ${eligibleLevels} of ${availableLevels} coverage levels`
        : 'No validated pattern at any coverage level',
    completedLevels: 'coverage levels completed',
    eligibleLevels: 'levels with validated, historically stable patterns',
    highestEligibleLevel: 'highest coverage level with eligible patterns',
    unavailableLevels: 'coverage levels unavailable',
    gridExplanation:
      'This is the full 50–100% grid result. Decision Lab changes category weights only when validated patterns repeat across multiple coverage levels.',
    strictEyebrow: 'STRICT 100% COVERAGE DETAIL',
    strictTitle: 'What happened at the 100% level?',
    strictStatusWithEvidence: 'Evidence repeated at 100% coverage',
    strictStatusWithoutEvidence: 'No reliable rule at 100% coverage',
    strictSurvivors: '100%-coverage rules that survived a second test',
    strictExplanation:
      'The details below describe only the strict 100% grid member. They do not replace the shared-grid result above.',
    sensitivityTitle: 'Coverage-level results',
    sensitivityExplanation:
      'Each row uses the same wallet-balanced engine. “Eligible” is local to that coverage level; Decision Lab still requires repetition across levels before changing weights.',
    sensitivityRange: '50% → 100% · 5% steps',
    stableEligibleHeader: 'Stable / eligible',
    strictRulesTitle: '100% coverage rule details',
    strictRulesExplanation:
      'These rules belong only to the strict 100% grid member. Click a rule for its explanation and visual summary.',
    strictRuleCountSuffix: 'at 100%',
    noStrictRules:
      'No rule survived at the 100% level. This does not mean the shared-grid discovery failed.',
    evidenceTitle: 'Per-rule evidence comparison',
    evidenceExplanation:
      'Winner rules are shown first: positive in discovery and validation when both effects are available. Choose All categories to inspect the complete evidence table.',
    evidenceCategoryFilter: 'Category',
    evidenceWinnerRules: 'Winner rules · positive in discovery and validation',
    evidenceAllCategories: 'All categories',
    evidenceUnknownCategory: 'Unknown / unmapped',
    evidenceSearch: 'Find a rule',
    evidenceSearchPlaceholder: 'Feature, condition, or status',
    evidenceEmpty: 'No rules match the selected filters.',
    currentResult: 'Current result matches the saved evidence.',
    staleResult: (time: string) =>
      `Showing the previous result from ${time}. New evidence is available; refresh discovery before relying on it.`,
    staleResultSafety: 'This older result is display-only and is not used by Decision Lab scoring.',
    remainingWork: (count: number) => `${count} coverage level${count === 1 ? '' : 's'} remaining`,
    evidenceFeature: 'Rule / feature',
    evidenceCategory: 'Decision Lab group',
    evidenceCondition: 'Condition',
    evidenceDiscoveryEffect: 'Discovery effect',
    evidenceValidationEffect: 'Validation effect',
    evidenceSamples: 'Samples D / V',
    evidenceWallets: 'Wallets D / V',
    evidenceGroups: 'Groups D / V',
    evidenceHistory: 'Historical blocks survived / total',
    evidenceStatus: 'Validation status',
    evidenceSignificance: 'Significance',
    evidenceWeighting: 'Weighting',
    evidencePromotion: 'Promoted / stable',
    evidenceLegend:
      'D / V means discovery / validation. “Validated” means the report explicitly marked a validation survivor; it is not a percentage success rate. Historical stability counts blocks that survived. Promoted is shown only when the report provides it. Effects are associations, not guaranteed profit.',
    exportPageData: 'Export all page data (.json)',
    promotedTitle: 'Promoted and historically stable patterns',
    promotedExplanation:
      'These are the actual rule names and conditions that survived validation and repeated across coverage levels. They are associations, not guaranteed profit and not yet a single golden rule.',
    promotedViewLabel: 'Show',
    promotedCrossCoverage: 'Cross-coverage promoted patterns',
    promotedCoverage: 'Coverage',
    promotedSupport: 'Supported at',
    promotedStability: 'Stable blocks',
    promotedEmpty: 'No promoted/stable patterns are available for this coverage view.',
    promotedLegend:
      'Cross-coverage patterns repeat as validation survivors with historical stability in at least two coverage reports. Counts at 90%, 95%, and 100% are shown from their respective cached reports.',
  },
} as const;

export const UI_STRINGS = strings;
